export const FIRST_LOAD_OPTIONS = "FIRST_LOAD_OPTIONS";
export const FIRST_VALUE_CHANGED = "FIRST_VALUE_CHANGED";
export const SECOND_VALUE_CHANGED = "SECOND_VALUE_CHANGED";
export const MIN_VALUE_CHANGED = "MIN_VALUE_CHANGED";
export const MAX_VALUE_CHANGED = "MAX_VALUE_CHANGED";
export const SCALE_CLICK = "SCALE_CLICK";
export const HAS_TIPS_CHANGED = "HAS_TIPS_CHANGED";
export const VERTICAL_CHANGED = "VERTICAL_CHANGED";
export const RANGE_CHANGED = "RANGE_CHANGED";
export const HAS_SCALE_CHANGED = "HAS_SCALE_CHANGED";
export const STEP_CHANGED = "STEP_CHANGED";
export const MAX_SCALE_NUMBERS_COUNT_CHANGED =
  "MAX_SCALE_NUMBERS_COUNT_CHANGED";
export const VIEW_CHANGED = "VIEW_CHANGED";
export const MODEL_CHANGED = "MODEL_CHANGED";
